package com.cs551clc.ecommerce.service.data.response;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;

import java.math.BigInteger;
import java.util.List;

public class OrderResponse {
    @DynamoDBHashKey(attributeName = "username")
    String username;

    @DynamoDBAutoGeneratedKey
    @DynamoDBRangeKey(attributeName = "orderId")
    String orderId;

    @DynamoDBAttribute
    List<String> productIdList;

    @DynamoDBAttribute
    List<BigInteger> productQtyList;


    String dateTime;
}
