package com.cs551clc.ecommerce.service.data.dynamodb;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.joda.time.DateTime;

import java.math.BigInteger;
import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName="Orders")
public class Order {
    @DynamoDBHashKey(attributeName = "username")
    String username;

    @DynamoDBAutoGeneratedKey
    @DynamoDBRangeKey(attributeName = "orderId")
    String orderId;

    @DynamoDBAttribute
    List<String> productIdList;

    @DynamoDBAttribute
    List<BigInteger> productQtyList;


    String dateTime;
}
