package com.cs551clc.ecommerce.service.data.dynamodb;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;



@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName="User")
public class User {

    @DynamoDBAutoGeneratedKey
    @DynamoDBIndexHashKey(attributeName = "sortKey", globalSecondaryIndexName = "sortKey")
    private String sortKey;

    @DynamoDBAttribute
    private String username;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private String password;

    @DynamoDBAttribute
    private String full_name;

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey
    private String primaryKey;
}
